spring.application.name=gestion-usuarios
spring.datasource.url=jdbc:oracle:thin:@rpwbb3wdet77677f_high?TNS_ADMIN=C:/Users/human/Desktop/gestion-usuarios/src/main/resources/wallet
spring.datasource.username=MICROS
spring.datasource.password=123456.MnEG$#
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.oracle.wallet.password=MNegonzalez1120%$

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect